### ISSUE TITLE
on wireguard post, weird markdown render problem

### ISSUE THREAD

**Issue by daveloyall** [Xe/site#20]
Hello.  This is what I see in my browser:

![image](https://user-images.githubusercontent.com/1524866/55495016-9c5ff080-5601-11e9-9e2c-d89ff948d063.png)

It's in the iOS client section.

Here is what shows up for those elements when I view them in "Developer Tools"...

![image](https://user-images.githubusercontent.com/1524866/55495125-db8e4180-5601-11e9-9354-95cc3c2dc9ee.png)

**Comment by Xe** [comment]
That's bizarre. I'm gonna dig into this. I think it might be interpreting the CIDR prefix as a fraction.

**Comment by Xe** [comment]
Looks like https://github.com/Xe/site/commit/36860136f77ca3d4cfc4d46cbe9665706ca64b46 fixed it. I'm making a note to myself in the future to only ever put cidr in `backticks`.

o/ thanks again
