### ISSUE TITLE
Invalid HTML: <meta> tag outside of <head>

### ISSUE THREAD

**Issue by vincentbernat** [Xe/site#264]
Hey!

I was looking at the code source of your blog post mentioning webmention and noticed you have some `<meta name=...>` tags outside of `<head>`. This is not valid. All these meta tags should be in `<head>`: https://validator.w3.org/nu/?doc=https%3A%2F%2Fchristine.website%2Fblog%2Fvarious-updates-2020-11-18.

**Comment by Xe** [comment]
I'll take a look, I think it's related to how I handle subtemplates. I'll try and fix it. 

However it does work in practice.
