### ISSUE TITLE
Series: TempleOS From the Bootloader Up

### ISSUE THREAD

**Issue by Xe** [Xe/site#29]
Something I've wanted to do for a while is explain how [TempleOS](http://templeos.org) works at a low level. An interesting way to do this with computer programs is to start from the entry point and work your way down. I plan to start from the bootloader and work my way into the compiler and kernel.

This would be from an entirely secular viewpoint. As a side effect of producing this series, I hope to create a "clean" version of TempleOS that doesn't have any biblical references.

**Comment by mcorossigo** [comment]
Hello @Xe 
Hoping not to bother you, can you share the status of this series, like a roadmap/plan or a lack of interest?
Thanks!

**Comment by Xe** [comment]
I don't want to get more weird TempleOS emails. Cancelling this series.
