### ISSUE TITLE
Low contrast code blocks.

### ISSUE THREAD

**Issue by adedomin** [Xe/site#377]
browser: Firefox 89.0 on Linux.

in fact. playing around with the default fonts in the browser, maybe this is a Noto Mono issue. changing the font to Droid San Mono appears to "fix" it.

Noto Sans Mono: 
![Screenshot from 2021-06-15 13-43-18](https://user-images.githubusercontent.com/6037590/122099190-b996c900-cddf-11eb-9cde-b04c417986f6.png)

Droid Sans Mono:
![Screenshot from 2021-06-15 13-42-55](https://user-images.githubusercontent.com/6037590/122099215-c0254080-cddf-11eb-8a62-4f2e4ab040e1.png)

either way the colors are probably not ideal. Maybe it's better to set an explicit preformatted text font family?

**Comment by Xe** [comment]
Can you check it now? I just pushed a massive improvement to how code blocks are rendered.

**Comment by adedomin** [comment]
LGTM :+1:
