### ISSUE TITLE
Is it possible to port it as a GitHub page?

### ISSUE THREAD

**Issue by underdogliu** [Xe/site#385]
Dear Xe,

First of all thanks for open-sourcing such beautiful website! I am thinking about using it as template for my personal website as well (I am currently using Jekyll). But I speculated from bottom of your page that it is hosted somewhere instead of being a Github page. Therefore, I'd like to ask if there is any tutorial/quick instruction available to re-distribute it into a Github page, or I may have to discover it by myself? 

Thanks in advance.

**Comment by Xe** [comment]
I have no idea. This is not a static site, it's a dynamic webapp written in Rust. I'm not sure what to suggest.

**Comment by underdogliu** [comment]
So is the site originated from something static or it was developed as a web app from the very beginning?

**Comment by Xe** [comment]
It was developed as a dynamic app from the beginning. Porting it to a static site would probably involve rewriting it from scratch.

**Comment by underdogliu** [comment]
Then definitely no bother. I think and css style would be helpful anyway though so I will see what I can do. Thanks again for answering! I will close the comment.
