### ISSUE TITLE
Stickers resolution is set too low

### ISSUE THREAD

**Issue by erdnaxe** [Xe/site#388]
#### Problem

Stickers are 512x512px which is fine (and nice for high density displays) but they are set to a resolution of 72x72pixels/inch.
This means that without specific scaling, the stickers are 18.062x18.062cm, which is a lot.

This is not a problem when browsing the blog directly on https://christine.website/ as CSS makes the stickers take 56x56px (standard display), but it is a problem when using a RSS reader.

![screenshot of miniflux](https://user-images.githubusercontent.com/2663216/129375890-ab317698-69d6-4338-bb87-a8aef1fd24dc.png)

#### Possible solution

One simple solution would be to raise the resolution to something like 288x288pixels/inch while keeping the same number of pixels. This would display 4.516x4.516cm stickers. In GIMP, the `Scale Image` tool can change this metadata.

**Comment by Xe** [comment]
Today I learned that is a thing! I'll take a look, thanks!

**Comment by Xe** [comment]
Fixed.
