### ISSUE TITLE
Grey text on lightmode is hard to read

### ISSUE THREAD

**Issue by rawleyfowler** [Xe/site#499]
On your new Salary Transparency page, on light mode it is hard to read the grey text against the background.

<img width="315" alt="Screen Shot 2022-06-21 at 09 47 39" src="https://user-images.githubusercontent.com/75388349/174842757-e28dddf2-2b72-4610-9937-e82c0aff74bb.png">

**Comment by princehabeeb** [comment]
can you please assign me this tax?

**Comment by Xe** [comment]
sure

**Comment by princehabeeb** [comment]
> sure

ok.. thanks
