### ISSUE TITLE
HLS videos don't work in some RSS readers

### ISSUE THREAD

**Issue by erdnaxe** [Xe/site#557]
Example of blogpost containing a video (https://xeiaso.net/blog/hls-experiment):
![image](https://user-images.githubusercontent.com/2663216/195269098-099987ff-9719-406a-a772-64badd6fb9d0.png)
Inspecting the video element reveals that it's just an empty `<video width="100%" controls=""></video>` tag.

What are the advantages of MPEG2-TS HLS (with H264 inside) for non-live videos compared to a `<video>` tag with a static {VP8+Opus} WebM container or {H264+AAC} MP4 container?
For iOS support, did you try HLS with another container (such as MP4 using {H264+AAC} codecs)?

**Comment by Xe** [comment]
I just pushed most of a fix in this commit: https://github.com/Xe/site/commit/0dec562c15add115377fe6905b43f3b33d735079

There are some cases I just won't be able to support, and I fear that RSS readers may be one of them unless your browser is able to understand the mime type `application/vnd.apple.mpegurl`. I don't know what else to suggest.

I added a fallback video too: https://cdn.xeiaso.net/file/christine-static/blog/HLSBROKE.mp4

I hope this at least fixes the bleeding.

> What are the advantages of MPEG2-TS HLS (with H264 inside) for non-live videos compared to a <video> tag with a static {VP8+Opus} WebM container or {H264+AAC} MP4 container?

XeDN works better with many smaller files than fewer big files. I need to fix a lot of XeDN's fundamental design, but this is mostly a hack designed to allow me to just get things working.
