### ISSUE TITLE
Ethical Ads fixedfooter blocks interacting with parts of the page

### ISSUE THREAD

**Issue by exdeejay** [Xe/site#568]
When an ad is visible on-screen, any text that's in line with the ad horizontally will be unselectable, and any scrollbars will be unable to be used. This seems to be because of a CSS rule that makes the container for the ad have a `width` of 100%

![image](https://user-images.githubusercontent.com/13634296/203439455-9c19653b-b0e6-4805-8a6a-a54ff2edb476.png)

I used the devtools to disable the `width` and `max-width` rules on the `[data-ea-style="fixedfooter"].loaded` CSS selector and it seemed to resolve the issue. I'd make a pull request but those rules appear to come from Ethical Ads's own Javascript.

**Comment by Xe** [comment]
I think I figured out what's wrong. I was using the wrong kind of ad placement. This was fixed in https://github.com/Xe/site/commit/83337b0d7f9165583e5b3a8ab2ee44adc8eadd41. Are you seeing it working as expected?

**Comment by exdeejay** [comment]
Sorry for the delayed response! I'm seeing the ad appear as a fixed footer now, which I believe is the intended layout.
