### ISSUE TITLE
Atom feed does not contain article content

### ISSUE THREAD

**Issue by lunik1** [Xe/site#609]
The Atom feed at https://xeiaso.net/blog.atom does not contain the content of articles, unlike the RSS feed at https://xeiaso.net/blog.rss.

**Comment by Xe** [comment]
Atom feeds let you have article content? I wasn't aware that this was the case. The atom spec is annoying to read.

**Comment by lunik1** [comment]
See e.g. the atom feed for the Rust blog https://blog.rust-lang.org/feed.xml

I think this is described in §4.1.3 of the spec
