### ISSUE TITLE
Share button not working in Firefox

### ISSUE THREAD

**Issue by RobertBendun** [Xe/site#726]
Throws TypeError with `navigator.canShare is not a function` which is true since this API is [not supported in Firefox](https://caniuse.com/web-share)

https://github.com/Xe/site/blob/a8f9a3c19d3b2f5121efeb7802bd33bf00ea11d7/lume/src/_includes/blog.njk#L44

**Comment by dym-sh** [comment]
fixed in #726

**Comment by dym-sh** [comment]
fixed in #733
