### ISSUE TITLE
Atom link (/blog.atom) redirects to blog/index.rss which 404s

### ISSUE THREAD

**Issue by bheesham** [Xe/site#727]
The bit in the index:

```
        <link rel="alternate" type="application/atom+xml" href="https://xeiaso.net/blog.atom">
```

**Comment by Xe** [comment]
I think I fixed this. Does this work for you? If it doesn't I can apply an advanced fix.

**Comment by bheesham** [comment]
Yep, this is fixed. Thanks! :tada: 

1. The `https://xeiaso.net/blog.atom` link no longer 404s, but redirects to `blog.rss`. This might trip feed readers up if they subscribe directly to `blog.atom` expecting an Atom feed, but I'm not sure.
2. The `link` to `blog.atom` has been removed from the index, so feed readers would be able to pick up a non-404 link. (The thing which tripped up my (badly written) reader specifically).
