### ISSUE TITLE
Broken links to blog series

### ISSUE THREAD

**Issue by ajhalili2006** [Xe/site#728]
I'm not sure if this is intended, but on some blog posts I read (especially regarding [freenode](https://xeiaso.net/blog/closed-projects-2022-03-24/) [from the Closed Project announcement post] and [this one](https://xeiaso.net/blog/elasticsearch/) [hint: _"This is why I've been disavowing my [articles about the V programming language](https://xeiaso.net/blog/series/v) among other things."_]) pointing to blog series has got me 404.

Apologies for this ticket, but feel free to reply/close anytime.

**Comment by Xe** [comment]
It's a known issue, I have yet to fix it.

**Comment by Xe** [comment]
Fixed in https://github.com/Xe/site/commit/df59f21fbc27ec37375613be35fd04eb3033189e
