### ISSUE TITLE
inconsistent usage of date formats

### ISSUE THREAD

**Issue by scarf005** [Xe/site#759]
![image](https://github.com/Xe/site/assets/54838975/20589f28-4354-4937-8021-2218751fe83b) ![image](https://github.com/Xe/site/assets/54838975/8699047b-9e1e-423b-b275-7dec3bce4d57)
[Recent Articles](https://xeiaso.net) on index pages uses iso8601 `YYYY-MM-DD` date format whereas other pages such as [Blog Articles](http://localhost:3000/blog/) use `MM/DD/YYYY` format. I'm wondering perhaps it's intended?

**Comment by Xe** [comment]
Fixed by porting the homepage to JSX.

**Comment by scarf005** [comment]
cool, also linking 629dfa70ebde5aa4ce70683a75ec7209accba3ea for ref.
